/*
 * LLMGS - LLM GameScript Info File
 * Generated by OpenTTD-LLM
 * This GameScript acts as a bridge between the LLM (via Admin Port) and the game
 */

class OpenTTDLLM extends AIInfo {
    function GetAuthor()      { return "Joost Plattel"; }
    function GetName()        { return "OpenTTDLLM"; }
    function GetDescription() { return "OpenTTDLLM is a bridge between the LLM and the game world."; }
    function GetVersion()     { return 1; }
    function GetDate()        { return "2026-01-20"; }
    function CreateInstance() { return "OpenTTDLLM"; }
    function GetShortName()   { return "OLLM"; }
    function GetAPIVersion()  { return "14"; }
}

RegisterAI(OpenTTDLLM());
